package it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6 2017-03-07T16:14:32.059+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ws.business.sigop.csi.it/", name = "ISigopservWS")
@XmlSeeAlso(
{ ObjectFactory.class })
public interface ISigopservWS
{

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiRecuperiPregressi", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiRecuperiPregressi")
  @ResponseWrapper(localName = "serviceEstraiRecuperiPregressiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiRecuperiPregressiResponse")
  @WebResult(name = "recuperi", targetNamespace = "")
  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.RecuperiPregressiVO serviceEstraiRecuperiPregressi(
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno)
      throws SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiPagamentiBeneficiariCompleto", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiariCompleto")
  @ResponseWrapper(localName = "serviceEstraiPagamentiBeneficiariCompletoResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiariCompletoResponse")
  @WebResult(name = "pagamenti", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.PagamentoBeneficiarioExtVO> serviceEstraiPagamentiBeneficiariCompleto(
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno,
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "interventi", targetNamespace = "") java.util.List<java.lang.Integer> interventi,
      @WebParam(name = "provincia", targetNamespace = "") java.lang.String provincia,
      @WebParam(name = "comune", targetNamespace = "") java.lang.String comune,
      @WebParam(name = "denominazione", targetNamespace = "") java.lang.String denominazione,
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "numDomanda", targetNamespace = "") java.lang.String numDomanda,
      @WebParam(name = "dataPresDomandaDal", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataPresDomandaDal,
      @WebParam(name = "dataPresDomandaAl", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataPresDomandaAl,
      @WebParam(name = "dataCreazListaDal", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataCreazListaDal,
      @WebParam(name = "dataCreazListaAl", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataCreazListaAl,
      @WebParam(name = "importoConcessoDa", targetNamespace = "") java.math.BigDecimal importoConcessoDa,
      @WebParam(name = "importoConcessoA", targetNamespace = "") java.math.BigDecimal importoConcessoA,
      @WebParam(name = "gestoriFascicolo", targetNamespace = "") java.util.List<java.lang.String> gestoriFascicolo,
      @WebParam(name = "extIdProcedimento", targetNamespace = "") java.lang.Integer extIdProcedimento,
      @WebParam(name = "sottoProcedimento", targetNamespace = "") java.lang.String sottoProcedimento,
      @WebParam(name = "organismiDelegati", targetNamespace = "") java.util.List<java.lang.Integer> organismiDelegati,
      @WebParam(name = "decreto", targetNamespace = "") java.lang.Integer decreto,
      @WebParam(name = "dataCreazDecretoDal", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataCreazDecretoDal,
      @WebParam(name = "dataCreazDecretoAl", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataCreazDecretoAl,
      @WebParam(name = "limiteNumRecord", targetNamespace = "") java.lang.Integer limiteNumRecord)
      throws SigopServiceException_Exception, SigopMaxRecordException_Exception,
      SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceScriviNuovoSoggettoRegistroAntimafia", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceScriviNuovoSoggettoRegistroAntimafia")
  @ResponseWrapper(localName = "serviceScriviNuovoSoggettoRegistroAntimafiaResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceScriviNuovoSoggettoRegistroAntimafiaResponse")
  @WebResult(name = "esito", targetNamespace = "")
  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.EsitoServizioVO serviceScriviNuovoSoggettoRegistroAntimafia(
      @WebParam(name = "idAzienda", targetNamespace = "") long idAzienda,
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "ragioneSociale", targetNamespace = "") java.lang.String ragioneSociale,
      @WebParam(name = "idAmmCompetenza", targetNamespace = "") java.lang.Long idAmmCompetenza,
      @WebParam(name = "idIntermediario", targetNamespace = "") java.lang.Long idIntermediario,
      @WebParam(name = "siglaPrefettura", targetNamespace = "") java.lang.String siglaPrefettura,
      @WebParam(name = "numeroProtocollo", targetNamespace = "") java.lang.Long numeroProtocollo,
      @WebParam(name = "dataProtocollo", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataProtocollo,
      @WebParam(name = "dataDocumento", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dataDocumento,
      @WebParam(name = "note", targetNamespace = "") java.lang.String note,
      @WebParam(name = "extIdProcedimento", targetNamespace = "") long extIdProcedimento,
      @WebParam(name = "utenteUltimoAggiornamento", targetNamespace = "") long utenteUltimoAggiornamento)
      throws SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceAggiornaCoordinateBancariePagamento", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceAggiornaCoordinateBancariePagamento")
  @ResponseWrapper(localName = "serviceAggiornaCoordinateBancariePagamentoResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceAggiornaCoordinateBancariePagamentoResponse")
  @WebResult(name = "esito", targetNamespace = "")
  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.EsitoServizioVO serviceAggiornaCoordinateBancariePagamento(
      @WebParam(name = "codiceDomanda", targetNamespace = "") java.lang.String codiceDomanda,
      @WebParam(name = "extIdSportello", targetNamespace = "") java.lang.Long extIdSportello,
      @WebParam(name = "numContoCorrente", targetNamespace = "") java.lang.String numContoCorrente,
      @WebParam(name = "cin", targetNamespace = "") java.lang.String cin,
      @WebParam(name = "cifraControllo", targetNamespace = "") java.lang.String cifraControllo,
      @WebParam(name = "iban", targetNamespace = "") java.lang.String iban,
      @WebParam(name = "extIdProcedimento", targetNamespace = "") java.lang.Integer extIdProcedimento,
      @WebParam(name = "utenteUltimoAggiornamento", targetNamespace = "") java.lang.Integer utenteUltimoAggiornamento)
      throws SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiFondi", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiFondi")
  @ResponseWrapper(localName = "serviceEstraiFondiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiFondiResponse")
  @WebResult(name = "fondi", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.FondoVO> serviceEstraiFondi()
      throws SigopServiceException_Exception, SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "testResources", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.TestResources")
  @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.TestResourcesResponse")
  @WebResult(name = "test", targetNamespace = "")
  public boolean testResources() throws SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceVisualizzaDebiti", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceVisualizzaDebiti")
  @ResponseWrapper(localName = "serviceVisualizzaDebitiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceVisualizzaDebitiResponse")
  @WebResult(name = "debiti", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SchedaCreditoVO> serviceVisualizzaDebiti(
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "tipoOrdinamento1", targetNamespace = "") java.lang.Integer tipoOrdinamento1,
      @WebParam(name = "tipoOrdinamento2", targetNamespace = "") java.lang.Integer tipoOrdinamento2,
      @WebParam(name = "tipoOrdinamento3", targetNamespace = "") java.lang.Integer tipoOrdinamento3,
      @WebParam(name = "tipoOrdinamento4", targetNamespace = "") java.lang.Integer tipoOrdinamento4)
      throws SigopServiceException_Exception, SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiDecreti", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiDecreti")
  @ResponseWrapper(localName = "serviceEstraiDecretiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiDecretiResponse")
  @WebResult(name = "decreti", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.DecretoVO> serviceEstraiDecreti(
      @WebParam(name = "extIdProcedimento", targetNamespace = "") java.lang.Integer extIdProcedimento,
      @WebParam(name = "sottoProcedimento", targetNamespace = "") java.lang.String sottoProcedimento)
      throws SigopServiceException_Exception, SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiPagamentiBeneficiari", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiari")
  @ResponseWrapper(localName = "serviceEstraiPagamentiBeneficiariResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiariResponse")
  @WebResult(name = "pagamenti", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.PagamentoBeneficiarioVO> serviceEstraiPagamentiBeneficiari(
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno,
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "interventi", targetNamespace = "") java.util.List<java.lang.Integer> interventi,
      @WebParam(name = "provincia", targetNamespace = "") java.lang.String provincia,
      @WebParam(name = "comune", targetNamespace = "") java.lang.String comune,
      @WebParam(name = "denominazione", targetNamespace = "") java.lang.String denominazione,
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "numDomanda", targetNamespace = "") java.lang.String numDomanda,
      @WebParam(name = "gestoriFascicolo", targetNamespace = "") java.util.List<java.lang.String> gestoriFascicolo,
      @WebParam(name = "extIdProcedimento", targetNamespace = "") java.lang.Integer extIdProcedimento,
      @WebParam(name = "sottoProcedimento", targetNamespace = "") java.lang.String sottoProcedimento,
      @WebParam(name = "organismiDelegati", targetNamespace = "") java.util.List<java.lang.Integer> organismiDelegati,
      @WebParam(name = "decreto", targetNamespace = "") java.lang.Integer decreto)
      throws SigopServiceException_Exception, SigopMaxRecordException_Exception,
      SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiPagamentiBeneficiariLimite", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiariLimite")
  @ResponseWrapper(localName = "serviceEstraiPagamentiBeneficiariLimiteResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiBeneficiariLimiteResponse")
  @WebResult(name = "pagamenti", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.PagamentoBeneficiarioVO> serviceEstraiPagamentiBeneficiariLimite(
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno,
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "interventi", targetNamespace = "") java.util.List<java.lang.Integer> interventi,
      @WebParam(name = "provincia", targetNamespace = "") java.lang.String provincia,
      @WebParam(name = "comune", targetNamespace = "") java.lang.String comune,
      @WebParam(name = "denominazione", targetNamespace = "") java.lang.String denominazione,
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "numDomanda", targetNamespace = "") java.lang.String numDomanda,
      @WebParam(name = "gestoriFascicolo", targetNamespace = "") java.util.List<java.lang.String> gestoriFascicolo,
      @WebParam(name = "extIdProcedimento", targetNamespace = "") java.lang.Integer extIdProcedimento,
      @WebParam(name = "sottoProcedimento", targetNamespace = "") java.lang.String sottoProcedimento,
      @WebParam(name = "organismiDelegati", targetNamespace = "") java.util.List<java.lang.Integer> organismiDelegati,
      @WebParam(name = "decreto", targetNamespace = "") java.lang.Integer decreto,
      @WebParam(name = "limiteNumRecord", targetNamespace = "") java.lang.Integer limiteNumRecord)
      throws SigopServiceException_Exception, SigopMaxRecordException_Exception,
      SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "isAlive", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.IsAlive")
  @ResponseWrapper(localName = "isAliveResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.IsAliveResponse")
  @WebResult(name = "alive", targetNamespace = "")
  public boolean isAlive();

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiPagamentiErogati", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiErogati")
  @ResponseWrapper(localName = "serviceEstraiPagamentiErogatiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiPagamentiErogatiResponse")
  @WebResult(name = "debiti", targetNamespace = "")
  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.PagamentiErogatiVO serviceEstraiPagamentiErogati(
      @WebParam(name = "cuaa", targetNamespace = "") java.lang.String cuaa,
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno)
      throws SigopSystemException_Exception;

  @WebMethod
  @RequestWrapper(localName = "serviceEstraiInterventi", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiInterventi")
  @ResponseWrapper(localName = "serviceEstraiInterventiResponse", targetNamespace = "http://ws.business.sigop.csi.it/", className = "it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.ServiceEstraiInterventiResponse")
  @WebResult(name = "interventi", targetNamespace = "")
  public java.util.List<it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.InterventoVO> serviceEstraiInterventi(
      @WebParam(name = "settore", targetNamespace = "") java.lang.String settore,
      @WebParam(name = "anno", targetNamespace = "") java.lang.Integer anno)
      throws SigopServiceException_Exception, SigopSystemException_Exception;
}
