
package it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.6 2017-03-07T16:14:32.043+01:00
 * Generated source version: 3.1.6
 */

@SuppressWarnings("serial")
@WebFault(name = "SigopServiceException", targetNamespace = "http://ws.business.sigop.csi.it/")
public class SigopServiceException_Exception extends Exception
{

  private it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopServiceException sigopServiceException;

  public SigopServiceException_Exception()
  {
    super();
  }

  public SigopServiceException_Exception(String message)
  {
    super(message);
  }

  public SigopServiceException_Exception(String message, Throwable cause)
  {
    super(message, cause);
  }

  public SigopServiceException_Exception(String message,
      it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopServiceException sigopServiceException)
  {
    super(message);
    this.sigopServiceException = sigopServiceException;
  }

  public SigopServiceException_Exception(String message,
      it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopServiceException sigopServiceException,
      Throwable cause)
  {
    super(message, cause);
    this.sigopServiceException = sigopServiceException;
  }

  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopServiceException getFaultInfo()
  {
    return this.sigopServiceException;
  }
}
